In [1]:
# Importing the necessary packages
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import random
import math

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

A popular wisdom states that more children are born during certain phases of the lunar cycle, especially during the full moon. A classification of the number of births according to the lunar cycle was done in 2005.
A sample of the number of births during different lunar cycles is given below.  
Is there a relationship between the lunar phase and the number of births?

In [15]:
dfmoon = pd.DataFrame(data={'lunar_phase': ['new moon', 'young crescent', 'first quarter', 'waxing moon', 'full moon', 'waning moon', 'last quarter', 'ashen moon'],
                            'number_of_days': [24, 152, 24, 149, 24, 150, 24, 152],
                            'number_of_births': [7680, 48442, 7579, 47814, 7711, 47595, 7733, 48230]})

dfmoon.head(10)

      lunar_phase  number_of_days  number_of_births
0        new moon              24              7680
1  young crescent             152             48442
2   first quarter              24              7579
3     waxing moon             149             47814
4       full moon              24              7711
5     waning moon             150             47595
6    last quarter              24              7733
7      ashen moon             152             48230

In [17]:
# print(np.sum([24, 152, 24, 149, 24, 150, 24, 152]))

observed = dfmoon['number_of_births']
totaal_aantal_dagen = dfmoon['number_of_days'].sum()

expected_p = dfmoon['number_of_days'] / totaal_aantal_dagen # theoretisch verwachte kansen
expected = expected_p * sum(observed) # Hoeveel zouden er geboren zijn als er GEEN verschil is tussen maanfases
expected

0     7649.236052
1    48445.161660
2     7649.236052
3    47489.007153
4     7649.236052
5    47807.725322
6     7649.236052
7    48445.161660
Name: number_of_days, dtype: float64

In [ ]:
#Stap 1
# H0 = Er is geen verschil in aantal geboortes tussen maanfases
# H1 = Er is wel een verschil in aantal geboortes tussen maanfases

In [21]:
# Stap 2
alpha = 0.05

In [30]:
# Stap 3: test stat chi2
# Stap 4: g, p
chi2, p = stats.chisquare(f_obs=observed, f_exp=expected)
degrees_of_freedom = len(dfmoon['lunar_phase']) - 1
g = stats.chi2.isf(0.05, df=degrees_of_freedom)

print("X2 = %.4f" % chi2)
print("p = %.4f" % p)
print("g = %.4f" % g)

X2 = 6.3111
p = 0.5039
g = 14.0671

In [24]:
# Stap 5: conclusie: p = 50% > 5% sign lvl = niet voldoende reden om H0 te verwerpen
# g = 14 % > chi2 (6.31%) = niet voldoende reden om H0 te verwerpen

In [31]:
# Extra: std residuals

dfmoon['stdres'] = (observed - expected) / np.sqrt(expected * (1-expected_p))
dfmoon

      lunar_phase  number_of_days  number_of_births    stdres
0        new moon              24              7680  0.357948
1  young crescent             152             48442 -0.016238
2   first quarter              24              7579 -0.817218
3     waxing moon             149             47814  1.681259
4       full moon              24              7711  0.718642
5     waning moon             150             47595 -1.097798
6    last quarter              24              7733  0.974619
7      ashen moon             152             48230 -1.105057

**Answers:**

- chi-square statistic $\chi^2 \approx$ 0.1129
- $p \approx$ 0.999996485