## Example Exam Questions Chapter 4

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats

## Exercise 1
Criminologists have long debated whether there is a relationship between weather conditions and the number of crimes committed. In 1988, an article “Is there a
Season for Homicide?” (Criminology, 1988: 287-296) classified 1361 homicides by season, resulting
in the data below.  
Is there an association between season and the number of murders committed?

In [8]:
dfmurders = pd.DataFrame(data={
    'season': ['winter', 'spring','summer','autumn'],
    'number_of_murders': [328, 334, 372, 327]
})

In [13]:
# Stap 1
# H0: geen verband tussen seizoenen en aantal moorden
# H1: wel een verband "" ""

# Stap 2
alpha = 0.05

# Stap 3: teststatistiek
# GOF-test
observed = dfmurders['number_of_murders']
expected_p = np.array([0.25,0.25,0.25,0.25])
expected = expected_p * sum(observed)

ch2, p = stats.chisquare(f_obs=observed, f_exp=expected)
# Stap 4: crit value
dof = len(observed) - 1
g = stats.chi2.isf(0.05, df=dof)
ch2, p, g

# Stap 5: p > alpha, en ch2 < g dus we hebben niet
# voldoende aanwijziging om H0 te verwerpen -> geen verband tussen seizoen en moorden

(np.float64(4.034533431300514),
 np.float64(0.25775920748891),
 np.float64(7.814727903251178))

## Exercise 2
A random sample of individuals was taken, and each individual was classified according to their level of education and their sense of spirituality.
Is there an association between the level of education and the sense of spirituality?

In [30]:
dfspirituality = pd.DataFrame(data={
    'sense_of_spirituality': ['lot', 'moderate','little','none'],
    'alfa_scientist': [56, 162, 198, 211],
    'beta_scientist': [56, 223, 243, 239],
    'not_scientist': [109, 164, 74, 28]
})
dfspirituality.head()

  sense_of_spirituality  alfa_scientist  beta_scientist  not_scientist
0                   lot              56              56            109
1              moderate             162             223            164
2                little             198             243             74
3                  none             211             239             28

In [31]:
# Tabel met 2x kwalitatieve var -> Chi2 of Cramer's V
# H0: er is geen verband tussen het type opleiding en geloof in spir
# H0: er is wel een verband tussen het type opleiding en geloof in spir

# Stap 2
alpha = 0.05

# Stap 3: test stat
dfspirituality = dfspirituality.drop('sense_of_spirituality', axis=1)

chi2, p, degrees_of_freedom, expected = stats.chi2_contingency(dfspirituality)
g = stats.chi2.isf(0.05, df=degrees_of_freedom)

print("Chi-squared     : %.4f" % chi2)
print("DOF     : %d" % degrees_of_freedom)
print("P-value     : %.4f" % p)
print("g     : %.4f" % g)

Chi-squared     : 213.2122
DOF     : 6
P-value     : 0.0000
g     : 12.5916

In [32]:
# Conclusie: er is voldoende aanwijzing om H0 te verwerpen
# Chi2 > g, p < alpha

In [34]:
dfspirituality

   alfa_scientist  beta_scientist  not_scientist
0              56              56            109
1             162             223            164
2             198             243             74
3             211             239             28

In [33]:
# TODO dit klopt niet (in-class), eens merge van rows proberen?
stats.contingency.association(dfspirituality, method="cramer")

0.24590359045026888

## Exercise 4

In an experiment, 150 patients were divided into three groups of 45, 45 and 60 patients each. Two groups were given a new drug in different doses and the third group was given a placebo. The way the patients felt after using the drug are shown in the data frame below. Is there evidence at the 5% significance level that there is a difference in the condition between the three groups of patients?

In [36]:
dfexperiment = pd.DataFrame(data={
    'state': ['better', 'equal', 'worse'],
    'placebo': [16, 20, 9],
    'half_dosis': [17, 18, 10],
    'full_dosis': [26, 20, 14]
}).set_index('state')
dfexperiment.head()

        placebo  half_dosis  full_dosis
state
better       16          17          26
equal        20          18          20
worse         9          10          14

In [37]:
chi2, p, degrees_of_freedom, expected = stats.chi2_contingency(dfexperiment)
g = stats.chi2.isf(0.05, df=degrees_of_freedom)

print("Chi-squared     : %.4f" % chi2)
print("DOF     : %d" % degrees_of_freedom)
print("P-value     : %.4f" % p)
print("g     : %.4f" % g)

Chi-squared     : 1.4169
DOF     : 4
P-value     : 0.8412
g     : 9.4877

In [ ]:
# Conclusie: Chi2 < g, P > alpha -> niet genoeg aanwijzing om H0 te verwerpen
# Geen verband tussen gekregen dosis en conditie